name: ClassicPress Directory Coding Standard checks.

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: CPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CPCS get rules
        run: |
          wget -O phpcs.xml https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml
          sed -i '/^\t<!-- start config -->.*/a\
            <file>.</file>\
          ' phpcs.xml
          sed -i 's/MY_DOMAIN/wc-vip-club/g' phpcs.xml
          mv phpcs.xml phpcs.xml.dist
      - name: CPCS checks
        uses: 10up/wpcs-action@v1.7.0
        with:
          use_local_config: 'true'
          enable_warnings: 'true'
          extra_args: '--report-json=./phpcs.json'
      - name: Update summary
        if: always()
        run: |
          npm i -g https://github.com/10up/phpcs-json-to-md/tarball/master
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
